apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: producer-go
spec:
  template:
    metadata:
      labels:
        app: producer-go
    spec:
      containers:
        - name: producer-go
          image: "producer-go:latest"
  replicas: 1
  triggers:
    # The ConfigChange trigger creates a new replication controller whenever
    # changes are detected in the pod template of the deployment configuration.
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "producer-go"
        from:
          kind: "ImageStreamTag"
          name: "producer-go:latest"
  strategy: 
    # The strategy of deployment is of type rolling, which means that one pod at
    # a time will be replaced.
    type: "Rolling"
  paused: false 
  # Up to 2 revisions of the Docker image will be kept in the registry, in case
  # a rollback would be needed.
  revisionHistoryLimit: 9
  minReadySeconds: 0
