apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: fabric8-streams-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    # See
    # https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html/using_amq_streams_on_openshift_container_platform/assembly-deployment-configuration-str#assembly-kafka-broker-configuration-deployment-configuration-kafka
    # and http://kafka.apache.org/20/documentation.html#brokerconfigs
    config:
      # The replication factor for the offsets topic (set higher to ensure
      # availability). Internal topic creation will fail until the cluster size
      # meets this replication factor requirement.
      offsets.topic.replication.factor: 3
      # The replication factor for the transaction topic (set higher to ensure
      # availability). Internal topic creation will fail until the cluster size
      # meets this replication factor requirement.
      transaction.state.log.replication.factor: 3
      # Overridden min.insync.replicas config for the transaction topic.
      transaction.state.log.min.isr: 2
      # The number of hours to keep a log file before deleting it (in hours),
      # tertiary to log.retention.ms property
      log.retention.hours: 168
    storage:
      type: persistent-claim
      # Defines the size of the persistent volume claim, for example, "1000Gi". 
      size: 1Gi
      # Boolean value which specifies if the Persistent Volume Claim has to be
      # deleted when the cluster is undeployed. Default is false. 
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

